### ISSUE TITLE
[FEATURE] 딥러닝 서버 통신

### ISSUE THREAD

**Issue by aqswa** [go-ggle/voco-server#20]
# 📌 Issue
## Description
ML 서버에 요청 보내기
## TODO
- [x] ML 서버에 트레이닝 요청
- [x] ML 서버에 음성 데이터 전송
- [x] ML 서버에서 생성된 음성 데이터 S3에 저장
- [x] 트레이닝 완료 여부 알림
