### ISSUE TITLE
[FIX] 유저 인증 수정

### ISSUE THREAD

**Issue by doyeoo** [go-ggle/voco-server#47]
# 📌 Issue
## Description
유저 인증 관련 기능 및 응답 수정

## TODO
- [x] 비정상 토큰 에러코드 401 반환하기
- [x] 로그인 한 유저 객체 대신 userId 반환하기
- [x] 레포지토리 객체 id로 변경
